name: M4 CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted

    defaults:
      run:
        shell: cmd

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest Docker image
        run: |
          docker compose pull

      - name: Remove old container
        run: |
          docker rm -f cats-dogs-api >nul 2>&1
          exit /b 0

      - name: Deploy application
        run: |
          docker compose up -d

      - name: Check deployment
        run: |
          docker compose ps

      - name: Wait for application
        run: |
          timeout /t 10 /nobreak

      - name: Run smoke tests
        run: |
          python smoke_tests.py